spring:
  application:
    name: service-turbine
server:
  port: 8769
turbine:
  app-config: eureka-ribbon-client, eureka-feign-client
  combine-host-port: true
  aggregator:
    cluster-config: default
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
